#!/usr/bin/env python3
"""Generate device/etc/dash/Notify.js from tools/notify_table_r19917.json.

notify_table_r19917.json is the stock Launcher's check-control message table (mNotify000..418 in
QML unit 0x30220 of Launcher@20230517 r19917). EventHub.warningId indexes it; the stock UI shows
mNotify[id] (English = second '#' field) with icon qrc:/images/notify/<id, 3 digits>.png.
"""
import json, os
here = os.path.dirname(os.path.abspath(__file__))
tab = {t["id"]: t["en"] for t in json.load(open(os.path.join(here, "notify_table_r19917.json")))}
size = max(tab) + 1
rows = [json.dumps(tab.get(i, "")) for i in range(size)]
out = os.path.join(here, "..", "device", "etc", "dash", "Notify.js")
with open(out, "w") as f:
    f.write("// GENERATED by tools/gen_notify_js.py - do not edit.\n")
    f.write("// Check-control message id (EventHub.warningId) -> English text, from the car's Launcher.\n")
    f.write(".pragma library\n\nvar text = [\n    " + ",\n    ".join(rows) + "\n];\n\n")
    f.write('function name(id) { return id > 0 && id < text.length && text[id] !== "" ? text[id] : "Check vehicle (" + id + ")" }\n')
    f.write('function icon(id) { var n = id > 0 ? id : 1; return "images/notify/" + ("00" + n).slice(-3) + ".png" }\n')
    f.write('function critical(id) { return /fail|stop|brake|airbag|oil pressure|overheat|engine/i.test(name(id)) }\n')
print("wrote", out, size, "messages")
