#!/usr/bin/env python3
"""Generate device/etc/dash/Alarms.js from tools/alarm_table_r19917.json.

alarm_table_r19917.json is the stock Launcher's mAlarmIcon array (unit 0x223f0 in
Launcher@20230517 r19917, the build on the car): index = alarm ID, icon = qrc path inside the Launcher.
"""
import json, os
here = os.path.dirname(os.path.abspath(__file__))
tab = json.load(open(os.path.join(here, "alarm_table_r19917.json")))   # the car runs Launcher@20230517 r19917
# Red = stop-the-car severity, everything else amber/green handled by the icon art itself.
RED = {2, 3, 4, 5, 6, 17, 18, 21, 22, 23, 25, 60, 65}
rows = []
for t in tab:
    # IDs 102-122 all carry a copy-pasted "No key detected" label in the stock table; only 101 is real.
    name = t["en"] if t["en"].isascii() else ""
    if name == "No key detected" and t["id"] != 101:
        name = ""
    rows.append('    [%s, %s, %s]' % (json.dumps(t["icon"]), json.dumps(name), "true" if t["id"] in RED else "false"))
out = os.path.join(here, "..", "device", "etc", "dash", "Alarms.js")
with open(out, "w") as f:
    f.write("// GENERATED by tools/gen_alarms_js.py - do not edit.\n")
    f.write("// Alarm ID -> [qrc icon path, English name, critical]. IDs come from EventHub.alarmTable / warningId.\n")
    f.write(".pragma library\n\nvar table = [\n" + ",\n".join(rows) + "\n];\n\n")
    f.write("function icon(id) { return id > 0 && id < table.length && table[id][0] !== \"\" ? table[id][0] : \"images/alarm/ico_jinggao.png\" }\n")
    f.write("function name(id) { return id > 0 && id < table.length && table[id][1] !== \"\" ? table[id][1] : \"Warning \" + id }\n")
    f.write("function critical(id) { return id > 0 && id < table.length && table[id][2] }\n")
print("wrote", out, len(rows), "alarms")
